# Generated by Django 3.2.13 on 2022-05-26 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['id'], 'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='create_at',
        ),
        migrations.AddField(
            model_name='note',
            name='date_plan',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 0, 9, 16, 448345), verbose_name='Плановая дата'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(default='', verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Публично'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
    ]
